title: |
  SEEngineers - Southeast Engineers
email: your-email@example.com
description: >-
  With a combined 70 plus years of experience, Southeast Engineers has become a
  market leader in a wide range of engineering services.
baseurl: /
url: /
include:
  - _pages
  - _data
  - _services
name: Southeast Engineers
favicon: assets/img/favicon.ico
lang: en
author: Southeast Engineers
disqus:
google_analytics:
social:
  name: Facebook
  links:
    - https://www.facebook.com/
logo:
permalink: /:title
-scope:
   type: pages
   path: _pages/index.html
   values:
   permalink:
locale: en_us
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
