url: https://seengineers.com
include:
  - _pages
  - _data
  - _services
  - _portfolio
name: Southeast Engineers
favicon: assets/img/favicon.ico
lang: en
author: Southeast Engineers
permalink: "/:title/"
defaults:
- scope:
    path: /assets/vendor/aos/demo/async.html
  value:
    sitemap: false
  -scope:
  path: ""
  values:
    layout: default
    _options:
      content: &content_defaults
        uploads_dir: "uploads/:title"
        format: p h1 h2 h3 h4 h5 h6 div
        styles: /assets/css/theme.css
        undo: true
        redo: true
        left: text-left
        center: text-center
        right: text-right
        justify: justify-content-center
        bold: true
        italic: true
        underline: true
        strike: true
        subscript: false
        superscript: false
        blockquote: true
        table: true
        copyformatting: true
        removeformat: true
        numberedlist: true
        bulletedlist: true
        outdent: false
        indent: false
        image: true
        link: true
        embed: true
collections:
  services:
     output: false
     custom_permalink_placeholders: ["type"]
     permalink: /services/:title
-scope:
   type: pages
   path: _pages/index.html
   values:
   permalink:
locale: en_us
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll_custom_permalink

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
