_schema: _schema
paths:
  uploads: uploads
  dam_uploads: ''
  static: assets/images
  dam_static: ''
  collections: ''
  data: _data
  layouts: _layouts
  includes: _includes
  pages: _pages
collections_config:
  posts:
    path: _posts
    icon: notes
    output: true
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: _pages
    icon: notes
    output: true
    filter: strict
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  categories:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  img_url:
    type: image
    cascade: true
  ga_id:
    type: text
    label: Google Analytics ID
    cascade: true
  head_code:
    type: html
    options:
      allow_resize: true
      allow_custom_markup: false
      remove_custom_markup: false
      initial_height: 320
      code: true
      image_size_attributes: true
    label: Header Code
    cascade: true
  layout:
    type: auto
    hidden: true
    cascade: true
  body_code:
    type: html
    options:
      allow_resize: true
      allow_custom_markup: false
      remove_custom_markup: false
      initial_height: 320
      code: true
      image_size_attributes: true
    label: Body Code
    cascade: true
  footer_code:
    type: html
    options:
      allow_resize: true
      allow_custom_markup: false
      remove_custom_markup: false
      initial_height: 320
      code: true
      image_size_attributes: true
    label: Footer Code
    cascade: true
  images:
    type: image
    cascade: true
_select_data:
  jekyll-archives:
    layout: archive
    enabled: []
    permalinks:
      year: /:year/
      month: /:year/:month/
      day: /:year/:month/:day/
      tag: /tag/:name/
      category: /category/:name/
  archives: []
_editables:
  text:
    allow_custom_markup: true
    remove_custom_markup: true
    bold: true
    copyformatting: true
    italic: true
    link: true
    paths:
    redo:
    removeformat:
    strike: true
    subscript:
    superscript:
    underline: true
    undo:
  block:
    allow_custom_markup: false
    remove_custom_markup: false
    blockquote: true
    bold: true
    bulletedlist:
    center:
    code:
    copyformatting:
    correct_orientation:
    embed:
    expandable:
    format:
    height:
    horizontalrule:
    image:
    image_size_attributes: true
    indent:
    italic:
    justify:
    left:
    link:
    mime_type:
    numberedlist:
    outdent:
    paths:
    redo:
    removeformat:
    resize_style: contain
    right:
    snippet:
    strike:
    styles:
    subscript:
    superscript:
    table:
    underline:
    undo:
    width:
  image:
    correct_orientation:
    expandable: true
    height:
    image_size_attributes: true
    mime_type:
    paths:
    resize_style: cover
    width:
timezone: Etc/UTC
pages:
  path: ''
  output: true
  filter: strict
