source:
pages:
  path: ''
  output: true
  filter: strict
paths:
  uploads: uploads
  dam_uploads: ''
  static: ''
  dam_static: ''
  collections: ''
  data: _data
  layouts: _layouts
  includes: _includes
  pages: _pages
collections_config:
  posts:
    path: _posts
    output: true
    icon: notes
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: _pages
    output: true
    filter: strict
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  categories:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
_select_data:
  jekyll-archives:
    layout: archive
    enabled: []
    permalinks:
      year: /:year/
      month: /:year/:month/
      day: /:year/:month/:day/
      tag: /tag/:name/
      category: /category/:name/
  archives: []
_editables:
  text:
    allow_custom_markup: true
    remove_custom_markup: true
    bold: true
    copyformatting: true
    italic: true
    link: true
    paths:
    redo:
    removeformat:
    strike: true
    subscript:
    superscript:
    underline: true
    undo:
  block:
    allow_custom_markup: false
    remove_custom_markup: false
    blockquote: true
    bold: true
    bulletedlist:
    center:
    code:
    copyformatting:
    correct_orientation:
    embed:
    expandable:
    format:
    height:
    horizontalrule:
    image:
    image_size_attributes: true
    indent:
    italic:
    justify:
    left:
    link:
    mime_type:
    numberedlist:
    outdent:
    paths:
    redo:
    removeformat:
    resize_style: contain
    right:
    snippet:
    strike:
    styles:
    subscript:
    superscript:
    table:
    underline:
    undo:
    width:
  image:
    correct_orientation:
    expandable: true
    height:
    image_size_attributes: true
    mime_type:
    paths:
    resize_style: cover
    width:
data_config: {}
timezone: Etc/UTC
